"""Add generated_comments table

Revision ID: 2b39600da833
Revises: 09184a6fb376
Create Date: 2026-01-20 12:44:31.214982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b39600da833'
down_revision: Union[str, Sequence[str], None] = '09184a6fb376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_content', sa.Text(), nullable=True),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_comments_id'), 'generated_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_comments_id'), table_name='generated_comments')
    op.drop_table('generated_comments')
    # ### end Alembic commands ###
