version: '3.8'

services:
  ftp:
    image: fauria/vsftpd
    container_name: ftp_service
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=ftppassword
      - PASV_ADDRESS=0.0.0.0
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
    volumes:
      - ./ftpdata:/home/vsftpd
    networks:
      - actappon_wordpress_network
    restart: unless-stopped

networks:
  actappon_wordpress_network:
    external: true

