services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    expose:
      - 80
    networks:
      - external_network
    volumes:
      - ${HOME}:/srv
      - ./database/filebrowser.db:/database/filebrowser.db
      - ./config/settings.json:/config/settings.json
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

networks:
  external_network:
    name: actappon_wordpress_network
    external: true
