worker_processes auto;

events {
    worker_connections 1024;
}

http {
    map $http_origin $cors_origin {
        default 0;
        "~https://www.albaniaconnect.com" $http_origin;
        "~https://albaniaconnect.com" $http_origin;
    }

    map $http_x_forwarded_proto $forwarded_proto {
        default $http_x_forwarded_proto;
        "" $scheme;
    }

    include /etc/nginx/cloudflare-real-ip.conf;
    include /etc/nginx/cloudflare-source-ip.conf;
    real_ip_header CF-Connecting-IP;
    real_ip_recursive on;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 100M;

    server {
        listen 80;
        server_name actappon.com;

        include /etc/nginx/cloudflare-allow.conf;

        location / {
            proxy_pass http://wordpress:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $forwarded_proto;

            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 120s;
            send_timeout 120s;
        }

        location = /xmlrpc.php {
            deny all;
            access_log off;
            log_not_found off;
        }
    }

    server {
        listen 80;
        server_name filebrowser.actappon.com;

        include /etc/nginx/cloudflare-allow.conf;

        location / {
            proxy_pass http://filebrowser:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $forwarded_proto;

            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 120s;
            send_timeout 120s;
        }
    }

    server {
        listen 80;
        server_name monitor.actappon.com;

        include /etc/nginx/cloudflare-allow.conf;

        location / {
            proxy_pass http://monitor:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $forwarded_proto;

            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 120s;
            send_timeout 120s;
        }
    }
}
